version: "3.9"

services:
    api:
        container_name: api
        image: laravel-api-container
        build:
            context: ./svyazkom-test-server
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db

    db:
        container_name: vodokachka-db
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - pgdata:/var/lib/postgresql/data

    client:
        container_name: client
        build:
            context: ./svyazkom-test-client
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "3000:80"

volumes:
    pgdata: {}
